name: Lua Format and Lint

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 lua5.4-dev

      - name: Install LuaRocks
        run: |
          sudo apt-get install -y luarocks
          luarocks --version
      - name: Add LuaRocks bin to PATH
        run: echo "$HOME/.luarocks/bin" >> $GITHUB_PATH

      - name: Install luacheck
        run: luarocks install --local luacheck

      - name: Run luacheck
        run: luacheck .

      - name: Install stylua
        run: |
          curl -sSL https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip -o stylua.zip
          unzip stylua.zip -d stylua-bin
          chmod +x stylua-bin/stylua
          sudo mv stylua-bin/stylua /usr/local/bin/

      - name: Run stylua
        run: stylua .
